# Generated by Django 5.1.4 on 2024-12-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog poszt'},
        ),
    ]
