# Generated by Django 5.1.4 on 2024-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_episodepage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='apple_podcast_url',
            field=models.URLField(blank=True, verbose_name='Apple Podcast url'),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='sound_cloud_url',
            field=models.URLField(blank=True, verbose_name='SoundCloud url'),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='spotify_url',
            field=models.URLField(blank=True, verbose_name='Spotify url'),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube url'),
        ),
    ]
