# Generated by Django 5.1.4 on 2024-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_episodepage_apple_podcast_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
