# Generated by Django 5.1.4 on 2024-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_episodepage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='authors_old',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
