# Generated by Django 5.1.4 on 2024-12-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_episodepage_authors_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='duration',
            field=models.DurationField(),
        ),
    ]
