# Generated by Django 5.1.4 on 2024-12-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_episodepage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='audio_direct_url',
            field=models.URLField(blank=True, verbose_name='Audio direct url'),
        ),
    ]
