# Generated by Django 5.1.4 on 2024-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='recent_blogs_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
