# Generated by Django 5.1.4 on 2024-12-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='podcast_app_links',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='recent_blogs_title',
        ),
    ]
