# Generated by Django 5.1.4 on 2024-12-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='apple_podcast_url',
            field=models.URLField(blank=True, verbose_name='Apple Podcast url'),
        ),
    ]
